/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QrRouteImport } from './routes/qr'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinksRouteImport } from './routes/links'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExpiredRouteImport } from './routes/expired'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClickLimitRouteImport } from './routes/click-limit'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GateShortCodeRouteImport } from './routes/gate.$shortCode'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpiredRoute = ExpiredRouteImport.update({
  id: '/expired',
  path: '/expired',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClickLimitRoute = ClickLimitRouteImport.update({
  id: '/click-limit',
  path: '/click-limit',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GateShortCodeRoute = GateShortCodeRouteImport.update({
  id: '/gate/$shortCode',
  path: '/gate/$shortCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bookmarks': typeof BookmarksRoute
  '/click-limit': typeof ClickLimitRoute
  '/dashboard': typeof DashboardRoute
  '/expired': typeof ExpiredRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/qr': typeof QrRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/gate/$shortCode': typeof GateShortCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bookmarks': typeof BookmarksRoute
  '/click-limit': typeof ClickLimitRoute
  '/dashboard': typeof DashboardRoute
  '/expired': typeof ExpiredRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/qr': typeof QrRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/gate/$shortCode': typeof GateShortCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bookmarks': typeof BookmarksRoute
  '/click-limit': typeof ClickLimitRoute
  '/dashboard': typeof DashboardRoute
  '/expired': typeof ExpiredRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/qr': typeof QrRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/gate/$shortCode': typeof GateShortCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/bookmarks'
    | '/click-limit'
    | '/dashboard'
    | '/expired'
    | '/forgot-password'
    | '/links'
    | '/login'
    | '/qr'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/gate/$shortCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/bookmarks'
    | '/click-limit'
    | '/dashboard'
    | '/expired'
    | '/forgot-password'
    | '/links'
    | '/login'
    | '/qr'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/gate/$shortCode'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/bookmarks'
    | '/click-limit'
    | '/dashboard'
    | '/expired'
    | '/forgot-password'
    | '/links'
    | '/login'
    | '/qr'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/gate/$shortCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BookmarksRoute: typeof BookmarksRoute
  ClickLimitRoute: typeof ClickLimitRoute
  DashboardRoute: typeof DashboardRoute
  ExpiredRoute: typeof ExpiredRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LinksRoute: typeof LinksRoute
  LoginRoute: typeof LoginRoute
  QrRoute: typeof QrRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  GateShortCodeRoute: typeof GateShortCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expired': {
      id: '/expired'
      path: '/expired'
      fullPath: '/expired'
      preLoaderRoute: typeof ExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/click-limit': {
      id: '/click-limit'
      path: '/click-limit'
      fullPath: '/click-limit'
      preLoaderRoute: typeof ClickLimitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate/$shortCode': {
      id: '/gate/$shortCode'
      path: '/gate/$shortCode'
      fullPath: '/gate/$shortCode'
      preLoaderRoute: typeof GateShortCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BookmarksRoute: BookmarksRoute,
  ClickLimitRoute: ClickLimitRoute,
  DashboardRoute: DashboardRoute,
  ExpiredRoute: ExpiredRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LinksRoute: LinksRoute,
  LoginRoute: LoginRoute,
  QrRoute: QrRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  GateShortCodeRoute: GateShortCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
